// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFPfSc1sofHoxKby2h4wwjKgzuGhcuiCk',
    appId: '1:197487231418:web:placeholder',
    messagingSenderId: '197487231418',
    projectId: 'ai-trip-planner-26100',
    authDomain: 'ai-trip-planner-26100.firebaseapp.com',
    storageBucket: 'ai-trip-planner-26100.firebasestorage.app',
    measurementId: 'G-placeholder',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFPfSc1sofHoxKby2h4wwjKgzuGhcuiCk',
    appId: '1:197487231418:android:62ea2772366c8eddd3dd83',
    messagingSenderId: '197487231418',
    projectId: 'ai-trip-planner-26100',
    storageBucket: 'ai-trip-planner-26100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY_HERE',
    appId: 'YOUR_IOS_APP_ID_HERE',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE',
    projectId: 'ai-trip-planner-26100',
    storageBucket: 'ai-trip-planner-26100.firebasestorage.app',
    iosBundleId: 'com.example.aiTripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY_HERE',
    appId: 'YOUR_MACOS_APP_ID_HERE',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE',
    projectId: 'ai-trip-planner-26100',
    storageBucket: 'ai-trip-planner-26100.firebasestorage.app',
    iosBundleId: 'com.example.aiTripPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFPfSc1sofHoxKby2h4wwjKgzuGhcuiCk',
    appId: '1:197487231418:windows:placeholder',
    messagingSenderId: '197487231418',
    projectId: 'ai-trip-planner-26100',
    authDomain: 'ai-trip-planner-26100.firebaseapp.com',
    storageBucket: 'ai-trip-planner-26100.firebasestorage.app',
    measurementId: 'G-placeholder',
  );
}
